version: '3.9'

networks:
  medallero_default:
    name: medallero_default
    external: true

services:
  tests:
    build: 
      context: .
      dockerfile: Dockerfile_tests
  web:
    build:
      context: .
      dockerfile: Dockerfile_web
    ports:
      - "35000:35000"
    networks:
      - medallero_default
    depends_on:
      - tests
  backoffice:
    build: 
      context: .
      dockerfile: Dockerfile_backoffice
    ports:
      - "35001:35001"
    networks:
      - medallero_default
    depends_on:
      - tests
