version: '3.9'

services:
  web-tests:
    build: .
    ports:
      - "5002:5002"
    command: bash -c "cd infrastructure && npm install && npm run test" &
    volumes:
      - "./:/usr/src/app"
  web:
    build: .
    ports:
      - "35000:35000"
    depends_on:
      - tests
    command: bash -c "cd web && npm install && npm run build && npm run start" &