version: '3.9'

services:
  tests:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    depends_on:
      - tests
    command: npm run build